### ISSUE TITLE
运行python3 login.py出错，求大佬指教

### ISSUE THREAD

**Issue by ppp626ppp** [DogeZhang/auto-sign#5]
2021-02-02 19:14:42 {'tenantId': 'fzu', 'login-url': 'http://id.fzu.edu.cn/authserver/login?service=https%3A%2F%2Ffzu.campusphere.net%2Fportal%2Flogin', 'host': 'fzu.campusphere.net'}
2021-02-02 19:14:42 正在获取验证码。。。
Traceback (most recent call last):
  File "login.py", line 462, in <module>
    login()
  File "login.py", line 426, in login
    getMessageCode()
  File "login.py", line 152, in getMessageCode
    errMsg = res.json()['errMsg']
  File "D:\新建文件夹\biancheng\2021-02-01-01-59-43-auto-sign-main\auto-sign-main\requests\models.py", line 898, in
json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by wxyttty** [comment]
这个他早就没有维护了，现在福大已经可以云端登录了，找通用的账号密码登录的就好了

**Comment by Sophiaxixi** [comment]
> 这个他早就没有维护了，现在福大已经可以云端登录了，找通用的账号密码登录的就好了

请问哪里找这个通用的账号密码呢
